"use client";

import { useMemo, useState } from "react";
import { ArrowUpRight, BedDouble, Building2, CheckCircle2, Inbox, Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { AdminSidebar } from "./admin-sidebar";
import { ContentForm } from "./content-form";
import { RoomForm } from "./room-form";
import { StatCard } from "./stat-card";
import type { DemoHostel, DemoInquiry, DemoRoom } from "./types";

function formatGhs(amount: number) { return `GHS ${amount.toLocaleString("en-GH")}`; }
function timeAgo(timestamp: number) { const hours = Math.floor((Date.now() - timestamp) / 3600000); return hours < 1 ? "Less than an hour ago" : `${hours}h ago`; }

export function HotelAppWorkspace({ hostels, rooms, inquiries, preview = false, onSaveRoom, onUpdateInquiry }: { hostels: DemoHostel[]; rooms: DemoRoom[]; inquiries: DemoInquiry[]; preview?: boolean; onSaveRoom?: (roomId: string, values: { price: number; available: number; accepting: boolean }) => Promise<void>; onUpdateInquiry?: (inquiryId: string, status: DemoInquiry["status"]) => Promise<void> }) {
  const [active, setActive] = useState("Overview");
  const hostel = hostels[0];
  const [roomValues, setRoomValues] = useState(rooms);
  const [inquiryValues, setInquiryValues] = useState(inquiries);
  const openRooms = roomValues.reduce((total, room) => total + (room.accepting ? room.availableCount : 0), 0);
  const newInquiries = inquiryValues.filter((inquiry) => inquiry.status === "new").length;
  const booked = inquiryValues.filter((inquiry) => inquiry.status === "booked").length;
  const selectedRooms = useMemo(() => roomValues.filter((room) => room.hostelId === hostel?.id), [roomValues, hostel?.id]);

  async function saveRoom(room: DemoRoom, values: { price: number; available: number; accepting: boolean }) {
    if (onSaveRoom) await onSaveRoom(room._id, values);
    setRoomValues((current) => current.map((item) => item._id === room._id ? { ...item, pricePerSemester: values.price, availableCount: values.available, accepting: values.accepting } : item));
  }
  async function updateInquiry(id: string, status: DemoInquiry["status"]) {
    if (onUpdateInquiry) await onUpdateInquiry(id, status);
    setInquiryValues((current) => current.map((inquiry) => inquiry._id === id ? { ...inquiry, status } : inquiry));
  }

  return <div className="min-h-screen bg-slate-50 text-slate-950"><AdminSidebar active={active} onActiveChange={setActive} /><main className="min-h-screen lg:pl-64"><div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:px-10"><header className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="mb-3 flex items-center gap-2 text-xs font-medium text-slate-400"><span>hostel/</span><span>/</span><span className="text-slate-600">{active.toLowerCase()}</span>{preview ? <span className="ml-2 rounded-full bg-amber-100 px-2 py-1 text-amber-700">Preview data</span> : null}</div><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">{active === "Overview" ? "Good morning, Kelvin." : active}</h1><p className="mt-2 max-w-xl text-sm text-slate-500">{active === "Overview" ? "Here&apos;s what needs your attention across the hostels you manage." : active === "Clients" ? "Keep every client site live, current, and easy to renew." : active === "Inquiries" ? "Follow up quickly and keep every lead moving." : "The content layer behind each client&apos;s public site."}</p></div><div className="flex gap-2"><Button variant="secondary"><ArrowUpRight className="h-4 w-4" />View public site</Button><Button><Building2 className="h-4 w-4" />Add client</Button></div></header>

{active === "Overview" ? <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Live clients" value={String(hostels.filter((item) => item.status === "live").length)} hint="Across your workspace" icon={Building2} /><StatCard label="Open rooms" value={String(openRooms)} hint="Ready to be filled" icon={BedDouble} /><StatCard label="New inquiries" value={String(newInquiries)} hint="Need a response" icon={Inbox} /><StatCard label="Booked this cycle" value={String(booked)} hint="From tracked inquiries" icon={CheckCircle2} /></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_1fr]"><Card><CardHeader className="flex-row items-start justify-between"><div><CardTitle>Client portfolio</CardTitle><CardDescription>Live status and the next renewal moment.</CardDescription></div><Button variant="ghost" size="sm" onClick={() => setActive("Clients")}>View all <ArrowUpRight className="h-3.5 w-3.5" /></Button></CardHeader><CardContent className="space-y-1">{hostels.map((item) => <div key={item.id} className="flex flex-col gap-3 rounded-xl p-3 transition-colors hover:bg-slate-50 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100 text-sm font-bold text-slate-600">{item.name.slice(0, 1)}</div><div><p className="text-sm font-semibold">{item.name}</p><p className="text-xs text-slate-400">{item.customDomain ?? `${item.slug}.vercel.app`}</p></div></div><div className="flex items-center gap-3"><Badge variant={item.status}>{item.status}</Badge><span className="text-xs text-slate-400">Renews {item.renewalDate ?? "not set"}</span></div></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Recent activity</CardTitle><CardDescription>The latest movement across your portfolio.</CardDescription></CardHeader><CardContent className="space-y-4">{inquiryValues.slice(0, 3).map((inquiry) => <div key={inquiry._id} className="flex gap-3"><div className="mt-0.5 rounded-full bg-sky-50 p-2 text-sky-600"><Users className="h-3.5 w-3.5" /></div><div className="min-w-0"><p className="text-sm"><span className="font-semibold">{inquiry.name}</span> asked about {inquiry.roomName}.</p><p className="mt-1 text-xs text-slate-400">{timeAgo(inquiry.createdAt)} · {inquiry.source === "wa" ? "WhatsApp" : "Website form"}</p></div></div>)}</CardContent></Card></div></> : null}

{active === "Clients" ? <div className="grid gap-6"><Card><CardHeader><CardTitle>Client sites</CardTitle><CardDescription>One view of status, domain, and renewal health.</CardDescription></CardHeader><CardContent className="space-y-3">{hostels.map((item) => <div key={item.id} className="grid gap-4 rounded-xl border border-slate-100 p-4 md:grid-cols-[1.5fr_1fr_auto_auto] md:items-center"><div><p className="font-semibold">{item.name}</p><p className="mt-1 text-xs text-slate-400">{item.tagline}</p></div><div><p className="text-xs text-slate-400">Domain</p><p className="mt-1 text-sm">{item.customDomain ?? "Not connected"}</p></div><div><p className="text-xs text-slate-400">Renewal</p><p className="mt-1 text-sm">{item.renewalDate ?? "Not set"}</p></div><Badge variant={item.status}>{item.status}</Badge></div>)}</CardContent></Card><ContentForm /></div> : null}

{active === "Inquiries" ? <Card><CardHeader><CardTitle>Inquiry inbox</CardTitle><CardDescription>Track every lead from first contact to booking.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-175 text-left text-sm"><thead className="border-b border-slate-200 text-xs text-slate-400"><tr><th className="pb-3 font-medium">Lead</th><th className="pb-3 font-medium">Room</th><th className="pb-3 font-medium">Move-in</th><th className="pb-3 font-medium">Received</th><th className="pb-3 font-medium">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{inquiryValues.map((inquiry) => <tr key={inquiry._id}><td className="py-4"><p className="font-semibold">{inquiry.name}</p><p className="mt-1 text-xs text-slate-400">{inquiry.phone}</p></td><td className="py-4 text-slate-600">{inquiry.roomName}</td><td className="py-4 text-slate-600">{inquiry.moveInDate}</td><td className="py-4 text-slate-500">{timeAgo(inquiry.createdAt)}</td><td className="py-4"><select aria-label={`Update ${inquiry.name} status`} value={inquiry.status} onChange={(event) => updateInquiry(inquiry._id, event.target.value as DemoInquiry["status"])} className="rounded-lg border border-slate-200 bg-white px-2 py-1.5 text-xs font-semibold"><option value="new">New</option><option value="contacted">Contacted</option><option value="booked">Booked</option></select></td></tr>)}</tbody></table></div></CardContent></Card> : null}

{active === "Content" ? <Tabs defaultValue="rooms"><TabsList><TabsTrigger value="rooms">Rooms & availability</TabsTrigger><TabsTrigger value="copy">Copy & media</TabsTrigger></TabsList><TabsContent value="rooms" className="mt-5"><Card><CardHeader><CardTitle>{hostel?.name ?? "Client"} rooms</CardTitle><CardDescription>Structured edits only. Every price and availability change is recorded.</CardDescription></CardHeader><CardContent className="space-y-4">{selectedRooms.map((room) => <div key={room._id}><div className="mb-3 flex items-center justify-between"><div><p className="font-semibold">{room.name}</p><p className="mt-1 text-xs text-slate-400">{room.occupancy}-person · {room.bathType} bath · current {formatGhs(room.pricePerSemester)}</p></div>{room.accepting ? <Badge variant="live">Accepting</Badge> : <Badge variant="paused">Closed</Badge>}</div><RoomForm room={room} onSave={(values) => saveRoom(room, values)} />{room._id !== selectedRooms[selectedRooms.length - 1]?._id ? <Separator className="mt-4" /> : null}</div>)}</CardContent></Card></TabsContent><TabsContent value="copy" className="mt-5"><ContentForm /></TabsContent></Tabs> : null}
</div></main></div>;
}
